
database:
  host: mongo
  port: 27017
  username: root
  password: root
  name: translation
  collection: translation_cache

ollama:
  url: http://ollama:11434/api/generate
  

kafka:
  kafka_broker: kafka:9093
  topic_in: topic_in
  topic_out: topic_out
  group_id: translation_group
  rest_api_url: http://sync:5000/translation-endpoints/api/v1/translate