FROM python:3.9


WORKDIR /model-api

COPY . . 

# installing dep
RUN pip install flask flask-restx torch transformers SentencePiece pymongo sacremoses PyYAML python-json-logger
# or pip install --no-cache-dir -r requirements.txt

# exposing port 
EXPOSE 5000

CMD [ "python", "./app.py"]

