FROM python:3.9


WORKDIR /model-api

COPY . . 


# installing dep
RUN pip install  --no-cache-dir -r requirements.txt
# or flask flask-restx torch transformers SentencePiece pymongo sacremoses PyYAML python-json-logger ollama

# exposing port 
EXPOSE 5000

CMD [ "python", "./app.py"]

